sonar.projectKey=MSA39HN-G3_health-rec-system
sonar.organization=ppr501-fpt

sonar.sources=app
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/.venv/**,**/scripts/**

sonar.language=py
sonar.sourceEncoding=UTF-8
