"""add booking and scheduling tables

Revision ID: 0adf3e3f6a25
Revises: c447d587eb9b
Create Date: 2026-07-08 15:25:45.499236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0adf3e3f6a25'
down_revision = 'c447d587eb9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), server_default='CREATED', nullable=False),
    sa.Column('current_step', sa.Integer(), server_default='1', nullable=False),
    sa.Column('free_text_symptom', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_sessions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_sessions_patient_id'), ['patient_id'], unique=False)

    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=255), server_default='ppr501.22-recommend', nullable=False),
    sa.Column('is_selected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rank BETWEEN 1 AND 3', name='check_ai_recommendations_rank'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['booking_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'department_id', name='uq_ai_recommendations_session_dept'),
    sa.UniqueConstraint('session_id', 'rank', name='uq_ai_recommendations_session_rank')
    )
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_recommendations_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_session_id'), ['session_id'], unique=False)

    op.create_table('booking_session_symptoms',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('symptom_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['booking_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'symptom_id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=64), server_default='EXAMINATION', nullable=False),
    sa.Column('building', sa.String(length=255), nullable=True),
    sa.Column('floor', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='OPEN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index('idx_rooms_dept_open', ['department_id'], unique=False, postgresql_where=sa.text("status = 'OPEN'"))
        batch_op.create_index(batch_op.f('ix_rooms_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_rooms_department_id'), ['department_id'], unique=False)

    op.create_table('doctor_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('max_patients_per_slot', sa.Integer(), server_default='1', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='check_doctor_schedules_time'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_schedules_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_schedules_room_id'), ['room_id'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('symptom_note', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='check_appointments_time'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['doctor_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['booking_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'appointment_date', 'start_time', name='uq_appointments_doctor_slot')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_appointments_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_session_id'), ['session_id'], unique=False)

    op.create_table('appointment_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_status_history_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_status_history_changed_by'), ['changed_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_status_history_changed_by'))
        batch_op.drop_index(batch_op.f('ix_appointment_status_history_appointment_id'))

    op.drop_table('appointment_status_history')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_session_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_room_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_department_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_code'))

    op.drop_table('appointments')
    with op.batch_alter_table('doctor_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_schedules_room_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_schedules_doctor_id'))

    op.drop_table('doctor_schedules')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_department_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_code'))
        batch_op.drop_index('idx_rooms_dept_open', postgresql_where=sa.text("status = 'OPEN'"))

    op.drop_table('rooms')
    op.drop_table('booking_session_symptoms')
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_session_id'))
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_department_id'))

    op.drop_table('ai_recommendations')
    with op.batch_alter_table('booking_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_sessions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_booking_sessions_created_by_user_id'))

    op.drop_table('booking_sessions')
    # ### end Alembic commands ###
