"""add health record symptoms

Revision ID: 16437349b16a
Revises: 9cd1021a43b9
Create Date: 2026-07-10 05:11:38.712480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16437349b16a'
down_revision = '9cd1021a43b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_record_symptoms',
    sa.Column('health_record_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['health_record_id'], ['health_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('health_record_id', 'symptom_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_record_symptoms')
    # ### end Alembic commands ###
