"""add patient medical fields

Revision ID: 9cd1021a43b9
Revises: xxxx_d4e5f6a7b8c9
Create Date: 2026-07-10 04:04:42.388330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd1021a43b9'
down_revision = 'xxxx_d4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_ratings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_doctor_rating_appointment'), type_='unique')
        batch_op.create_unique_constraint('uq_doctor_rating_appointment', ['patient_id', 'appointment_id'])

    with op.batch_alter_table('doctor_statistics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_doctor_statistics_doctor'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_doctor_statistics_doctor_id'))
        batch_op.create_index(batch_op.f('ix_doctor_statistics_doctor_id'), ['doctor_id'], unique=True)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('medical_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('allergies')
        batch_op.drop_column('medical_history')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('blood_type')

    with op.batch_alter_table('doctor_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_statistics_doctor_id'))
        batch_op.create_index(batch_op.f('ix_doctor_statistics_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_doctor_statistics_doctor'), ['doctor_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('doctor_ratings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_doctor_rating_appointment', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_doctor_rating_appointment'), ['appointment_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
