"""add symptom_categories, symptoms and symptom_department_map

Revision ID: fc1ad6bbf544
Revises: f3b8c2d6a510
Create Date: 2026-07-01 20:39:12.796739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc1ad6bbf544'
down_revision = 'f3b8c2d6a510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptoms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['symptom_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptoms_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptoms_code'), ['code'], unique=True)

    op.create_table('symptom_department_map',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symptom_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symptom_id', 'department_id', name='uq_symptom_department')
    )
    with op.batch_alter_table('symptom_department_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptom_department_map_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_department_map_symptom_id'), ['symptom_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom_department_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_department_map_symptom_id'))
        batch_op.drop_index(batch_op.f('ix_symptom_department_map_department_id'))

    op.drop_table('symptom_department_map')
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptoms_code'))
        batch_op.drop_index(batch_op.f('ix_symptoms_category_id'))

    op.drop_table('symptoms')
    op.drop_table('symptom_categories')
    # ### end Alembic commands ###
